name: Crawl SuperLotto638 latest

on:
  schedule:
    # 每週一、四 23:00（台灣時間）
    - cron: '0 15 * * 1,4'
  workflow_dispatch:

permissions:
  contents: write                 # 讓 Actions 可以 push 回 repo

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # ① 安裝 requests（Runner 通常已內建，但保險起見）
      - name: Ensure requests
        run: python -m pip install --upgrade requests

      # ② 直接抓官方 JSON，取最新一期
      - name: Generate latest.json
        run: |
          python - <<'PY'
          import json, pathlib, requests
          url = 'https://www.taiwanlottery.com.tw/Lotto/SuperLotto638/history.aspx?type=history&format=json'
          data = requests.get(url, timeout=30).json()['list'][0]
          path = pathlib.Path('data/superlotto638')
          path.mkdir(parents=True, exist_ok=True)
          with open(path / 'latest.json', 'w', encoding='utf-8') as f:
              json.dump(data, f, ensure_ascii=False)
          PY

      # ③ Commit & push
      - name: Commit & push
        run: |
          git config user.name  github-actions
          git config user.email actions@users.noreply.github.com
          git add data/superlotto638/latest.json
          git commit -m "auto: update superlotto638" || echo "no changes"
          git push
