name: Crawl SuperLotto638 latest

on:
  schedule:
    # 每週一、四 23:00（台灣時間）
    - cron: '0 15 * * 1,4'
  workflow_dispatch:          # 允許手動執行

permissions:
  contents: write             # 讓 Actions 可以 git push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1) 取回程式碼
      - uses: actions/checkout@v4

      # 2) 安裝 Python 3.11
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3) 安裝爬蟲（直接從 GitHub）
      - name: Install crawler
        run: |
          python -m pip install --upgrade pip
          pip install git+https://github.com/stu01509/TaiwanLotteryCrawler.git

      # 4) 產生 latest.json
      - name: Generate latest.json
        run: |
          python - <<'PY'
          from TaiwanLottery import SuperLotto638
          import json, pathlib
          data = SuperLotto638().latest()
          path = pathlib.Path('data/superlotto638')
          path.mkdir(parents=True, exist_ok=True)
          with open(path / 'latest.json', 'w', encoding='utf-8') as f:
              json.dump(data, f, ensure_ascii=False)
          PY

      # 5) Commit 並推回 master
      - name: Commit & push
        run: |
          git config user.name  github-actions
          git config user.email actions@users.noreply.github.com
          git add data/superlotto638/latest.json
          git commit -m "auto: update superlotto638" || echo "no changes"
          git push
